### ISSUE TITLE
"DB Error: no such table" when installing in Wordpress 4.1.1 / CivicCRM 4.4

### ISSUE THREAD

**Issue by joesalowitz** [veda-consulting/uk.co.vedaconsulting.mailchimp#127] opened 2015-02-27 22:43 UTC
I received a DB Error when trying to install via the Wordpress interface. I can replicate this every time I try to install. Any ideas?

**Comment by veda-consulting** [comment] 2015-07-17 13:31
@joesalowitz we can't reproduce this, could you confirm the exact steps your taking?

**Comment by veda-consulting** [comment] 2015-08-12 10:51
@joesalowitz we're closing as not heard anything back

**Closed by veda-consulting** 2015-08-12 10:51 UTC
