### ISSUE TITLE
Group Search Does Not Work With MailChimp Extension

### ISSUE THREAD

**Issue by stevekessler** [veda-consulting/uk.co.vedaconsulting.mailchimp#222] opened 2016-08-09 05:35 UTC
I am writing because I have found that when this extension is enabled that the search functions on the _Manage Groups_ does not work correctly. A member of the Cividesk development team looked into this and we believe it is an issue with using jQuery to add the column to the group listing tables.  

Please let me know if you need any more information to work on this. 

Thaks,
Steve

**Comment by xurizaemon** [comment] 2016-09-20 02:33
See notes on #224 including a workaround for 4.6 sites to disable the column added by Mailchimp extension.

**Comment by deepak-srivastava** [comment] 2016-12-23 17:49
Closing as duplicate of #224.

**Closed by deepak-srivastava** 2016-12-23 17:49 UTC
