### ISSUE TITLE
Updates to MC via API not forwarding to Civi

### ISSUE THREAD

**Issue by jason-vivid** [veda-consulting/uk.co.vedaconsulting.mailchimp#180] opened 2016-01-11 21:46 UTC
We have a client that recently added a service to their website to push email addresses captured on the site to Mailchimp.   New subscribers get pushed to Mailchimp effectively.  Those new subscribes do not continue on to CiviCRM however.  The via API block is checked in the webhook on MC.

**Comment by veda-consulting** [comment] 2016-01-12 09:58
@jason-vivid could you clarify the issue? Is it that mailchimp subscribers aren't ending up in CiviCRM?

**Comment by jason-vivid** [comment] 2016-01-18 18:35
Yes.  Subscribes from the popup on the webpage get added into mailchimp.  Those new subscribers  do not end up with a new record within Civi.

**Comment by mercurymotos** [comment] 2016-02-01 07:35
I'm having a similar issues - but it had nothing to do with the MailChimp API as a source.  I'm including my experience here as it may be related.

Everything moves FROM CiviCRM to MailChimp just fine, and CiviCRM was able to import all the names on the MailChimp list.  However if I manually unsubscribe (or delete) a subscriber in MailChimp then nothing happens in CiviCRM.

I _think_ I have the webhook correctly configured in MailChimp (and if I enter the URL into a browser I get a "null" response)(and the base "civicrm" page in WP is available... note that the instructions on that front could use some clarification).  And the MailChimp API log show a webhook call and it seems to succeed. - its marked with a big green check mark.

Any suggestions on what else I can look at to see where the problem is?

**Comment by Kajakaran** [comment] 2016-03-22 15:26
@jason-vivid 

 The via API block should not be checked in the webhook on MC in order to update  new subscribers From MC to Civi

**Comment by deepak-srivastava** [comment] 2016-12-23 17:40
Closing old ticket. Please re-open if the original query still exists in relation to v2.x release.

**Closed by deepak-srivastava** 2016-12-23 17:40 UTC
Labels: help wanted
